elkarte/addons

_posts/2015-02-24-Recent-Topics.md
I hope the file is correct. lol
=> Recent Topics addon

_posts/2015-04-01-Spoiler-Modern.md
Signed-off-by: inter <pmrtorrents@gmail.com>
=> Spoiler Modern

_posts/2015-06-18-BKE-Elk-Star-Trek-Avatars.md, _posts/2015-06-18-BKE-Elk-Star-Trek-DS9-Avatars.md, _posts/2015-06-18-BKE-Elk-Star-Trek-Men-Avatars.md, _posts/2015-06-18-BKE-Elk-Star-Trek-TNG-Avatars.md, _posts/2015-06-18-BKE-Elk-Star-Trek-TOS-Avatars.md, _posts/2015-06-18-BKE-Elk-Star-Trek-VOY-Avatars.md, _posts/2015-06-18-BKE-Elk-Star-Trek-Women-Avatars.md
=> More Avatar Packs

_includes/license.MD
We wouldn't want to make @Spuds edit his post, would we. =P
(More important, it's pretty illogical to have to write GPL 2.0 besides GPL 3.)
=> Add GPL2 to matching pattern

_includes/footer.html
=> Search errors need style

_posts/2016-10-28-BBC-html5-video-audio.md
Signed-off-by: inter <pmrtorrents@gmail.com>
=> Add html5 video audio bbcode

_posts/2017-01-23-Simple Audio Video Embedder.MD
Signed-off-by: VBGAMER45 <vbgamer45@gmail.com>
=> Simple Audio Video Embedder addon by vbgamer45

_posts/2017-01-24-ezGallery Lite.MD
Add ezGallery Lite
Signed-off-by: VBGAMER45 <vbgamer45@gmail.com>
=> Add ezGallery Lite

_posts/2017-01-25-Registered Links.MD
Signed-off-by: VBGAMER45 <vbgamer45@gmail.com>
=> Registered Links

_posts/2017-01-26-Download System Lite.MD
Signed-off-by: vbgamer45 <vbgamer45@gmail.com>
=> Download System Lite

_posts/2017-01-27-RSS Feed Poster.MD
Signed-off-by: vbgamer45 <vbgamer45@gmail.com>
=> RSS Feed Poster

_posts/2014-09-06-geoIP-Location.MD
=> ! rev up to only support 1.0.8+

_posts/2014-02-26-Descriptive-Links.MD, _posts/2014-04-17-FancyBox.MD, _posts/2014-04-17-Member Map.MD, _posts/2016-2-10- Block-Disposable-Email.MD, _posts/2017-03-25-External-Auth.MD
=> ! various minor updates

_posts/2017-11-07-FlarumStyle.MD
Signed-off-by: inter <pmrtorrents@gmail.com>
=> + Flarum Style

_posts/2017-12-22-PostgreSQL-cache.MD
Additional caching mechanism for ElkArte
=> Adding PostgreSQLCache for ElkArte

_posts/2017-12-22-PostgreSQL-cache.MD, _posts/2017-12-31-MySQL-cache.MD, _posts/2018-03-12-ExtImageProxy.MD, _posts/2018-04-14-StopForumSpam.MD
Updated all addon URL's to point to my website so latest version is always available to download without needing to update.
=> Updated all my addon URL's

_posts/2017-12-22-PostgreSQL-cache.MD, _posts/2017-12-31-MySQL-cache.MD, _posts/2018-03-12-ExtImageProxy.MD, _posts/2018-04-14-StopForumSpam.MD
Elkarte doesn't like the query url change to .zip so that it does'nt download as ?project=
=> Sorry! Elkarte doesn't like the query url change to .zip

_posts/2018-08-26-YAPortal.MD
=> Adding YAPortal

_posts/2019-03-02-Count-Child-Child-Boards-Posts.MD
Count Child Child Boards Posts addon
=> New addon Count Child Child Boards Posts

_posts/2020-12-07 Giphy For Elkarte.MD
=> Giphy for Elkarte addon

_posts/2021-04-21-OEmbed.MD
=> Added OEmbed
